<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="recetario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo" type="xs:string"/>
                            <xs:element name="nombre"  type="xs:string"/>
                            <xs:element name="categoria" type="xs:string"/>
                            <xs:element name="tiempo"  type="xs:integer"/>
                            <xs:element name="dificultad"    type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>